### ISSUE TITLE
config.json requests not taken

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [sanathp/StatusOK#57]
Using docker based setup and this is how I have in my Macbook pro 2019 and all three docker services working ok.

**config.json**
```
{
	"notifications": {
		"slack":{
			"channel":"#general",
			"username":"my-slack-user-name",
			"channelWebhookURL":"https://hooks.slack.com/services/1235435/4543543/5435435"
		}
	},
	"requests": [
		{
			"url": "https://serviceofmine.me",
			"requestType": "GET",
			"headers": {
				"Authorization": "Bearer ac2168444f4de69c27d6384ea2ccf61a49669be5a2fb037ccc1f"
			},
			"urlParams": {
				"name": "statusok"
			},
			"checkEvery": 1,
			"responseCode": 300,
			"responseTime": 500
		}
	]
}
```

**docker-compose.yml**

```
version: '2'
services:
  statusok:
#    build: sanathp/statusok
    build: ..
    volumes:
      - .:/config
    depends_on:
      - influxdb
  influxdb:
    image: tutum/influxdb:0.9
    environment:
      - PRE_CREATE_DB="statusok"
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
```

Since not able to pull `sanathp/statusok` image I used available dockerfile.

This does posts message to slack channel but its always sending only test notification and not the actual service error notice. 

I am missing some step, can you please point me in right direction
